import { defineStrings } from '../../i18n';

/**
 * This game's texts. `en` defines keys and argument types; `ar` must match.
 * Arabic: never assume the partner's gender (noun phrases like "طلقة من …", "بحر …").
 * GameError messages use the registered form "battleship.<key>".
 */
export const tg = defineStrings(
  'battleship',
  {
    name: 'Battleship',
    blurb: 'Hide your fleet, then take turns firing to sink your partner’s ships.',
    placeTitle: 'Place your ships',
    placeHint: 'Tap a ship to pick it, then tap where it should go. Or shuffle.',
    shuffle: '🎲 Shuffle',
    rotate: '↻ Rotate',
    ready: 'Lock in my fleet',
    waitPlace: (n: string) => `Waiting for ${n} to place ships…`,
    oppReady: (n: string) => `${n}’s fleet is ready.`,
    yourTurn: 'Your turn: fire at a square',
    theirSea: (n: string) => `${n}’s sea`,
    yourFleet: 'Your fleet',
    theirFleet: (n: string) => `${n}’s ships`,
    youHit: 'Hit! 🔥',
    youMiss: 'Splash, a miss 💧',
    youSunk: (len: number) => `You sank a ship of ${len}! 💥`,
    oppHit: (n: string) => `${n}’s shot: hit 🔥`,
    oppMiss: (n: string) => `${n}’s shot: miss 💧`,
    oppSunk: (n: string, len: number) => `${n} sank your ship of ${len} 💥`,
    square: (r: number, c: number) => `Row ${r}, column ${c}`,
    'err.notPlacing': 'The ships are already placed.',
    'err.placed': 'Your fleet is already locked in.',
    'err.badFleet': 'That fleet arrangement isn’t valid.',
    'err.badCell': 'That square isn’t in the sea.',
    'err.alreadyShot': 'You already fired at that square.',
  },
  {
    name: 'معركة السفن',
    blurb: 'خبّئ أسطولك، ثم تبادلا إطلاق النار لإغراق سفن الطرف الآخر.',
    placeTitle: 'رتّب سفنك',
    placeHint: 'اضغط على سفينة لاختيارها، ثم على مكانها الجديد. أو رتّبها عشوائياً.',
    shuffle: '🎲 عشوائي',
    rotate: '↻ تدوير',
    ready: 'تثبيت الأسطول',
    waitPlace: (n) => `بانتظار ترتيب سفن ${n}…`,
    oppReady: (n) => `أسطول ${n} جاهز.`,
    yourTurn: 'دورك: إطلاق النار على خانة',
    theirSea: (n) => `بحر ${n}`,
    yourFleet: 'أسطولك',
    theirFleet: (n) => `سفن ${n}`,
    youHit: 'إصابة! 🔥',
    youMiss: 'طلقة في الماء 💧',
    youSunk: (len) => `إغراق سفينة بطول ${len}! 💥`,
    oppHit: (n) => `طلقة من ${n}: إصابة 🔥`,
    oppMiss: (n) => `طلقة من ${n}: في الماء 💧`,
    oppSunk: (n, len) => `طلقة من ${n}: إغراق سفينتك بطول ${len} 💥`,
    square: (r, c) => `الصف ${r}، العمود ${c}`,
    'err.notPlacing': 'تم ترتيب السفن بالفعل.',
    'err.placed': 'أسطولك مثبّت بالفعل.',
    'err.badFleet': 'ترتيب الأسطول غير صالح.',
    'err.badCell': 'هذه الخانة خارج البحر.',
    'err.alreadyShot': 'سبق الإطلاق على هذه الخانة.',
  },
);
