import { defineStrings } from '../../i18n';

/** "1 card", "2 cards"… */
const cardsEn = (k: number) => (k === 1 ? '1 card' : `${k} cards`);
/** Arabic counted noun: ورقة واحدة، ورقتان، 3–10 أوراق، 11+ ورقة. */
const cardsAr = (k: number) => (k === 1 ? 'ورقة واحدة' : k === 2 ? 'ورقتان' : k >= 3 && k <= 10 ? `${k} أوراق` : `${k} ورقة`);
/** Keep "+30" or "2♣" left-to-right inside Arabic text (else it shows as "30+" or "♣2"). */
const ltr = (s: string) => `\u2066${s}\u2069`;

/**
 * This game's texts. `en` defines keys and argument types; `ar` must match.
 * Arabic: never assume a player's gender. In the messages `n` is "You"/"أنت" or a player's name,
 * used as a label before a colon (Arabic) or as the subject (English).
 * Words: the floor = الأرض (the face-up cards in the middle), the pack = الورق المتبقي,
 * a round (all 52 cards once) = جولة. Card names as Arab players say them: آس، ولد، بنت، شايب;
 * suits بستوني ♠، كبة ♥، ديناري ♦، سباتي ♣.
 */
export const tg = defineStrings(
  'basra',
  {
    name: 'Basra',
    blurb: 'The Egyptian card game: match a card on the floor or make its sum, sweep with a jack, and clear the floor for a basra (+10).',
    yourTurn: 'Your turn: play a card',
    roundOver: (r: number) => `Round ${r} is over`,
    round: (r: number) => `Round ${r}`,
    toTarget: 'first to 101',
    deckLeft: (k: number) => `${k} left`,
    floorLabel: 'The floor',
    floorEmpty: 'The floor is empty',
    handLabel: 'Your cards',
    pileOf: (k: number) => `${cardsEn(k)} taken`,
    handOf: (k: number) => `${cardsEn(k)} in hand`,
    carry: (k: number) => `+${k} waiting for most cards`,
    intro: 'Tap a card to see what it would take.',
    pick: 'Tap a card',
    playTakes: (k: number) => `Play: takes ${cardsEn(k)}`,
    playBasra: 'Play: Basra! +10',
    playDrop: 'Play: it stays on the floor',
    took: (n: string, k: number) => `${n} took ${cardsEn(k)}.`,
    dropped: (n: string) => `${n} put a card on the floor.`,
    sweptJack: (n: string, k: number) => `${n} swept the floor with a jack (${cardsEn(k)}).`,
    sweptSeven: (n: string, k: number) => `${n} swept the floor with the 7♦ (${cardsEn(k)}).`,
    basra: 'Basra! +10',
    dealt: 'New cards: 4 each.',
    dealtLast: 'The last 4 cards each!',
    leftover: (n: string, k: number) => `${cardsEn(k)} left on the floor went to ${n}.`,
    leftoverYou: (k: number) => `${cardsEn(k)} left on the floor went to you.`,
    tie: 'Level on cards: the 30 waits for the next round.',
    rowCards: 'Cards taken',
    rowMost: 'Most cards (+30)',
    rowAces: 'Aces (+1)',
    rowJacks: 'Jacks (+1)',
    rowTwo: '2♣ (+2)',
    rowTen: '10♦ (+3)',
    rowBasras: 'Basras (+10)',
    rowRound: 'This round',
    rowTotal: 'Game total',
    nextRound: 'Next round',
    lengthLabel: 'How long?',
    one: 'One round',
    oneHint: 'All 52 cards once: the higher score wins',
    full: 'To 101',
    fullHint: 'Round after round until someone reaches 101',
    cardName: (rank: string, suit: string) => `${rank} of ${suit}`,
    'rank.A': 'Ace',
    'rank.J': 'Jack',
    'rank.Q': 'Queen',
    'rank.K': 'King',
    'suit.S': 'spades',
    'suit.H': 'hearts',
    'suit.D': 'diamonds',
    'suit.C': 'clubs',
    'err.notInHand': 'That card isn’t in your hand.',
    'err.roundOver': 'This round is over.',
    'err.notYet': 'The round isn’t over yet.',
  },
  {
    name: 'باصرة',
    blurb: `لعبة الورق المصرية: ورقة تطابق ورقة على الأرض أو مجموعها، والولد يكنس الأرض كلها، وتنظيف الأرض بورقة واحدة باصرة (${ltr('+10')}).`,
    yourTurn: 'دورك: اختيار ورقة',
    roundOver: (r) => `انتهت الجولة ${r}`,
    round: (r) => `الجولة ${r}`,
    toTarget: 'حتى 101',
    deckLeft: (k) => `المتبقي ${k}`,
    floorLabel: 'الأرض',
    floorEmpty: 'الأرض فارغة',
    handLabel: 'أوراقك',
    pileOf: (k) => `المأخوذ: ${cardsAr(k)}`,
    handOf: (k) => `في اليد: ${cardsAr(k)}`,
    carry: (k) => `${ltr(`+${k}`)} تنتظر الأكثر أوراقاً`,
    intro: 'لمسة على ورقة تُظهر ما ستأخذه من الأرض.',
    pick: 'اختيار ورقة',
    playTakes: (k) => `لعب الورقة: ${cardsAr(k)} من الأرض`,
    playBasra: `لعب الورقة: باصرة! ${ltr('+10')}`,
    playDrop: 'لعب الورقة: تبقى على الأرض',
    took: (n, k) => `${n}: ${cardsAr(k)} من الأرض.`,
    dropped: (n) => `${n}: ورقة على الأرض.`,
    sweptJack: (n, k) => `${n}: الولد يكنس الأرض (${cardsAr(k)}).`,
    sweptSeven: (n, k) => `${n}: سبعة الديناري تكنس الأرض (${cardsAr(k)}).`,
    basra: `باصرة! ${ltr('+10')}`,
    dealt: 'توزيع جديد: 4 أوراق لكل لاعب.',
    dealtLast: 'آخر 4 أوراق لكل لاعب!',
    leftover: (n, k) => `بقية الأرض (${cardsAr(k)}) من نصيب ${n}.`,
    leftoverYou: (k) => `بقية الأرض (${cardsAr(k)}) من نصيبك.`,
    tie: 'تعادل في عدد الأوراق: الـ30 تنتظر الجولة التالية.',
    rowCards: 'الأوراق المأخوذة',
    rowMost: `الأكثر أوراقاً (${ltr('+30')})`,
    rowAces: `الآس (${ltr('+1')})`,
    rowJacks: `الولد (${ltr('+1')})`,
    rowTwo: `${ltr('2♣')} (${ltr('+2')})`,
    rowTen: `${ltr('10♦')} (${ltr('+3')})`,
    rowBasras: `الباصرة (${ltr('+10')})`,
    rowRound: 'هذه الجولة',
    rowTotal: 'المجموع',
    nextRound: 'الجولة التالية',
    lengthLabel: 'مدة اللعب',
    one: 'جولة واحدة',
    oneHint: 'الـ52 ورقة مرة واحدة: الفوز للنقاط الأعلى',
    full: 'حتى 101',
    fullHint: 'جولة بعد جولة حتى بلوغ 101 نقطة',
    cardName: (rank, suit) => `${rank} ${suit}`,
    'rank.A': 'آس',
    'rank.J': 'ولد',
    'rank.Q': 'بنت',
    'rank.K': 'شايب',
    'suit.S': 'بستوني',
    'suit.H': 'كبة',
    'suit.D': 'ديناري',
    'suit.C': 'سباتي',
    'err.notInHand': 'هذه الورقة ليست في يدك.',
    'err.roundOver': 'انتهت هذه الجولة.',
    'err.notYet': 'الجولة لم تنتهِ بعد.',
  },
);
