import { defineStrings } from '../../i18n';

/**
 * This game's texts. `en` defines keys and argument types; `ar` must match.
 * Arabic: never assume the partner's gender (noun phrases like "دور سامي", "آخر جملة من …").
 * GameError messages use the registered form "story.<key>", e.g. new GameError('story.err.empty').
 */
export const tg = defineStrings(
  'story',
  {
    name: 'Our Story',
    blurb: 'Take turns adding one sentence. You only see the last one, so the full story is a surprise.',
    yourTurn: 'Your turn: add a sentence',
    yourStart: 'Your turn: start the story',
    oppWriting: (n: string) => `${n} is writing…`,
    progress: (i: number, total: number) => `Sentence ${i} of ${total}`,
    partnerLast: (n: string) => `${n}’s last sentence`,
    startTitle: 'You start the story',
    startHint: 'Write the first sentence. It’s the only thing your partner will see.',
    example: 'For example:',
    opener1: 'On a strange morning…',
    opener2: 'Nobody expected the door to open, but…',
    opener3: 'It all started with a missing sock…',
    opener4: 'Once upon a time, in a very small kitchen…',
    opener5: 'The phone rang at midnight, and then…',
    opener6: 'Far away, on a tiny island…',
    phStart: 'Write the first sentence…',
    phNext: 'What happens next?',
    yourSentence: 'Your sentence',
    add: 'Add to the story',
    secret: (total: number) => `The whole story stays hidden until all ${total} sentences are in. Then comes the big reveal! 🎭`,
    ready: 'The story is ready! 📖',
    copyStory: 'Copy the story',
    copyPrompt: 'Copy the story:',
    'err.empty': 'Write a sentence first.',
    'err.tooLong': 'That sentence is too long (200 characters at most).',
  },
  {
    name: 'قصتنا',
    blurb: 'أضيفا جملة بالتناوب. لا يظهر لكما إلا آخر جملة، فتكون القصة كاملة مفاجأة.',
    yourTurn: 'دورك: أضف جملة',
    yourStart: 'دورك: ابدأ القصة',
    oppWriting: (n) => `دور ${n} في الكتابة…`,
    progress: (i, total) => `الجملة ${i} من ${total}`,
    partnerLast: (n) => `آخر جملة من ${n}`,
    startTitle: 'بداية القصة عندك',
    startHint: 'اكتب الجملة الأولى. وحدها ستظهر عند شريكك.',
    example: 'مثلاً:',
    opener1: 'في صباح غريب…',
    opener2: 'لم يتوقع أحد أن ينفتح الباب، لكن…',
    opener3: 'بدأ كل شيء بجورب مفقود…',
    opener4: 'كان يا ما كان، في مطبخ صغير جداً…',
    opener5: 'رنّ الهاتف عند منتصف الليل، ثم…',
    opener6: 'بعيداً، على جزيرة صغيرة…',
    phStart: 'اكتب الجملة الأولى…',
    phNext: 'ماذا حدث بعد ذلك؟',
    yourSentence: 'جملتك',
    add: 'إضافة إلى القصة',
    secret: (total) => `القصة كلها مخفية حتى تكتمل ${total} جمل، ثم يأتي الكشف الكبير! 🎭`,
    ready: 'القصة جاهزة! 📖',
    copyStory: 'نسخ القصة',
    copyPrompt: 'انسخ القصة:',
    'err.empty': 'اكتب جملة أولاً.',
    'err.tooLong': 'الجملة طويلة جداً (200 حرف كحد أقصى).',
  },
);
