import { defineStrings } from '../../i18n';

/** "n letters" with Arabic number agreement (1, 2, 3–10, 11+). */
const ahruf = (n: number) => (n === 1 ? 'حرف واحد' : n === 2 ? 'حرفان' : n <= 10 ? `${n} أحرف` : `${n} حرفاً`);

/**
 * This game's texts. `en` defines keys and argument types; `ar` must match.
 * Arabic: never assume the partner's gender (noun phrases like "كلمة سامي", "تقدّم …").
 * GameError messages use the registered form "wordle.<key>", e.g. new GameError('wordle.err.length').
 */
export const tg = defineStrings(
  'wordle',
  {
    name: 'Word Duel',
    blurb: 'Pick secret words for each other, then race to guess them in 6 tries. Arabic or English.',
    pickPrompt: 'Choose your secret word',
    pickHint: (n: string) => `Choose a word for ${n} to guess: Arabic or English, 3–7 letters.`,
    secretLabel: 'Your secret word',
    lockIn: 'Lock it in',
    count: (k: number) => (k === 1 ? '1 letter' : `${k} letters`),
    oppPicked: (n: string) => `${n} has chosen a word.`,
    waitWord: (n: string) => `Waiting for ${n}’s word…`,
    lockedHint: (n: string) => `Locked in. ${n} gets 6 tries to guess it.`,
    yourWord: 'Your word',
    oppWord: (n: string) => `${n}’s word`,
    guessIt: (len: number) => `Guess the word (${len} letters)`,
    waitFinish: (n: string) => `Waiting for ${n} to finish…`,
    guessLabel: 'Your guess',
    phAr: (len: number) => `${len} Arabic letters`,
    phEn: (len: number) => `${len} English letters`,
    guess: 'Guess',
    youSolved: (k: number) => `Well done! You got it on guess ${k}.`,
    youOut: 'Out of guesses. The word is revealed at the end.',
    tried: 'Letters tried',
    legendG: 'right spot',
    legendY: 'elsewhere in the word',
    legendX: 'not in the word',
    myGuesses: 'Your guesses',
    oppProgress: (n: string) => `${n}’s progress`,
    oppGuesses: (n: string) => `${n}’s guesses`,
    solvedOn: (k: number) => `Solved on guess ${k}`,
    outOf: 'Out of guesses',
    guessing: 'Still guessing…',
    'err.letters': 'Letters only: one word in Arabic or English, no spaces, numbers or symbols.',
    'err.length': 'The word needs 3 to 7 letters.',
    'err.guessLength': 'Your guess needs exactly as many letters as the word.',
    'err.locked': 'Your word is already locked in.',
    'err.done': 'You’ve finished guessing.',
  },
  {
    name: 'كلمة السر',
    blurb: 'اختارا كلمتين سريتين، ثم تسابقا في تخمين كلمة الطرف الآخر خلال 6 محاولات. بالعربية أو الإنجليزية.',
    pickPrompt: 'اختر كلمتك السرية',
    pickHint: (n) => `اختر كلمة سرية، وتخمينها مهمة ${n}: بالعربية أو الإنجليزية، من 3 إلى 7 أحرف.`,
    secretLabel: 'كلمتك السرية',
    lockIn: 'تثبيت الكلمة',
    count: (k) => ahruf(k),
    oppPicked: (n) => `كلمة ${n} جاهزة.`,
    waitWord: (n) => `بانتظار كلمة ${n}…`,
    lockedHint: (n) => `تم التثبيت. أمام ${n} ست محاولات لتخمينها.`,
    yourWord: 'كلمتك',
    oppWord: (n) => `كلمة ${n}`,
    guessIt: (len) => `خمّن الكلمة (${ahruf(len)})`,
    waitFinish: (n) => `ما زال التخمين مستمراً عند ${n}…`,
    guessLabel: 'تخمينك',
    phAr: (len) => `${ahruf(len)} عربية`,
    phEn: (len) => `${ahruf(len)} إنجليزية`,
    guess: 'خمّن',
    youSolved: (k) => `أحسنت! عرفت الكلمة في المحاولة ${k}.`,
    youOut: 'نفدت محاولاتك، وستظهر الكلمة في النهاية.',
    tried: 'الأحرف المجرّبة',
    legendG: 'في مكانه',
    legendY: 'في مكان آخر من الكلمة',
    legendX: 'ليس في الكلمة',
    myGuesses: 'تخميناتك',
    oppProgress: (n) => `تقدّم ${n}`,
    oppGuesses: (n) => `تخمينات ${n}`,
    solvedOn: (k) => `تم الحل في المحاولة ${k}`,
    outOf: 'نفدت المحاولات',
    guessing: 'التخمين مستمر…',
    'err.letters': 'أحرف فقط: كلمة واحدة بالعربية أو الإنجليزية، بلا مسافات أو أرقام أو رموز.',
    'err.length': 'يجب أن تتكون الكلمة من 3 إلى 7 أحرف.',
    'err.guessLength': 'يجب أن يكون عدد أحرف التخمين مساوياً لعدد أحرف الكلمة.',
    'err.locked': 'تم تثبيت كلمتك بالفعل.',
    'err.done': 'لقد أنهيت التخمين.',
  },
);
